export const curatorAbi = [
  {
    inputs: [{ internalType: 'address', name: '_curatorFactory', type: 'address' }],
    stateMutability: 'payable',
    type: 'constructor',
  },
  { inputs: [], name: 'ADDRESS_ZERO', type: 'error' },
  { inputs: [], name: 'ALREADY_INITIALIZED', type: 'error' },
  { inputs: [], name: 'CURATION_FROZEN', type: 'error' },
  { inputs: [], name: 'CURATION_PAUSED', type: 'error' },
  { inputs: [], name: 'DELEGATE_CALL_FAILED', type: 'error' },
  { inputs: [], name: 'INITIALIZING', type: 'error' },
  { inputs: [], name: 'INVALID_TARGET', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'impl', type: 'address' }],
    name: 'INVALID_UPGRADE',
    type: 'error',
  },
  { inputs: [], name: 'LISTING_EXISTS', type: 'error' },
  { inputs: [], name: 'NOT_INITIALIZING', type: 'error' },
  { inputs: [], name: 'ONLY_CALL', type: 'error' },
  { inputs: [], name: 'ONLY_CURATOR', type: 'error' },
  { inputs: [], name: 'ONLY_DELEGATECALL', type: 'error' },
  { inputs: [], name: 'ONLY_OWNER', type: 'error' },
  { inputs: [], name: 'ONLY_PENDING_OWNER', type: 'error' },
  { inputs: [], name: 'ONLY_PROXY', type: 'error' },
  { inputs: [], name: 'ONLY_UUPS', type: 'error' },
  { inputs: [], name: 'PASS_REQUIRED', type: 'error' },
  { inputs: [], name: 'UNSUPPORTED_UUID', type: 'error' },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'owner', type: 'address' }],
    name: 'CurationPaused',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'owner', type: 'address' }],
    name: 'CurationResumed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: 'version', type: 'uint256' },
    ],
    name: 'Initialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'curator', type: 'address' },
      { indexed: true, internalType: 'address', name: 'listing', type: 'address' },
    ],
    name: 'ListingAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'curator', type: 'address' },
      { indexed: true, internalType: 'address', name: 'listing', type: 'address' },
    ],
    name: 'ListingRemoved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'canceledOwner', type: 'address' },
    ],
    name: 'OwnerCanceled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'pendingOwner', type: 'address' },
    ],
    name: 'OwnerPending',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'prevOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnerUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: false, internalType: 'string', name: 'title', type: 'string' },
    ],
    name: 'TitleUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: false, internalType: 'address', name: 'tokenPass', type: 'address' },
    ],
    name: 'TokenPassUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: 'impl', type: 'address' }],
    name: 'Upgraded',
    type: 'event',
  },
  {
    inputs: [],
    name: 'acceptOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_listing', type: 'address' }],
    name: 'addListing',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'cancelOwnershipTransfer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getListings',
    outputs: [{ internalType: 'address[]', name: 'activeListings', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_owner', type: 'address' },
      { internalType: 'string', name: '_title', type: 'string' },
      { internalType: 'address', name: '_tokenPass', type: 'address' },
      { internalType: 'bool', name: '_pause', type: 'bool' },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_listing', type: 'address' }],
    name: 'ownerAddListing',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_listing', type: 'address' }],
    name: 'ownerRemoveListing',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pauseCuration',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pendingOwner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'proxiableUUID',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_listing', type: 'address' }],
    name: 'removeListing',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'resumeCuration',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newOwner', type: 'address' }],
    name: 'safeTransferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'title',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'tokenPass',
    outputs: [{ internalType: 'contract IERC721', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'string', name: '_title', type: 'string' }],
    name: 'updateTitle',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'contract IERC721', name: '_tokenPass', type: 'address' }],
    name: 'updateTokenPass',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newImpl', type: 'address' }],
    name: 'upgradeTo',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_newImpl', type: 'address' },
      { internalType: 'bytes', name: '_data', type: 'bytes' },
    ],
    name: 'upgradeToAndCall',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
] as const
